defaults:
  - _self_
#  - + module: module

backbone:
  choice: wav2vec2
  wav2vec2:
    size_choice: base
    base:
      path: 'D:\dcmt\model\hf\facebook\wav2vec2-base-960h'
      embedding_dim: 768
    large:
      path:
      embedding_dim: 1024
    is_freeze: True
classifier:
  num_labels: 8

criterion:
  loss_fn:
    choice: cross_entropy
  optimizer:
    choice: AdamW
    lr: 1e-4
  metrics:
    choice:
      - accuracy
      - f1_score
