device:


logger:
  config:
    learning_rate:
    batch_size:
    epoch:
  wandb:
    project:
    name:
    entity:


model:


dataloader:
  encoder:
    device:
    title:
    audio:
    text:
    image:
  dataset:
    train:
      batch_size:
    val:
      batch_size:


trainer:
  epoch:
    start:
    end:
  device:
  checkpoint:
    is_from_checkpoint:
    path_to_load:
    dir_to_save:






