# 一个配置文件的模板

data_module_config:
  train_dataset_config: dict
  train_dataloader_config: dict
  val_dataset_config: dict
  val_dataloader_config: dict


model_config:
  torch_model_name: str
  torch_model_config: dict
  loss_fn_name: str
  loss_fn_config: dict
  optimizer_name: str
  optimizer_config: dict
  metrics_configs_list:
    - metric_name: ''
      metric_kwargs: {}
    - metric_name: ''
      metric_kwargs: {}


trainer_config:
  trainer_base_config:
    default_root_dir: ''
    max_epochs: int
    accelerator: Literal[]
    devices: str
  callback_configs:
    - callback_name:
      callback_kwargs:
    - callback_name:
      callback_kwargs:
  logger_configs:
    - logger_name:
      logger_kwargs:
    - logger_name:
      logger_kwargs:

